export const homesList = [
  {
    title: 'Heart of Richmond/Master bedroom',
    id: 1,
    type: 'Private room',
    price: 25,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/13ba3b5f-89f7-4499-b26c-5a1bb28d60c5.jpg?aki_policy=xx_large'
  },
  {
    title: 'Heart of Richmond/Master bedroom',
    id: 2,
    type: 'Private room',
    price: 23,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/923a4feb-1563-461b-8b7b-8aaa121102be.jpg?aki_policy=xx_large'
  },
  {
    title: 'Heart of Richmond/Master bedroom',
    id: 3,
    type: 'Private room',
    price: 22,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/f940b68a-473e-4661-a204-560a9ff89264.jpg?aki_policy=xx_large'
  },
  {
    title: 'Heart of Richmond/Master bedroom',
    type: 'Private room',
    id: 4,
    price: 45,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/65bb8c9f-59d3-4227-aeea-01033937fc0c.jpg?aki_policy=xx_large'
  },
  {
    title: 'Heart of Richmond/Master bedroom',
    type: 'Private room',
    id: 5,
    price: 20,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/457b706f-eccb-4015-bdc7-d5a91dab250e.jpg?aki_policy=xx_large'
  },
  {
    title: 'Heart of Richmond/Master bedroom',
    type: 'Private room',
    id: 6,
    price: 22,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/f7d71c17-9463-43d4-8fda-4428d07d6482.jpg?aki_policy=xx_large'
  },
  {
    title: 'Heart of Richmond/Master bedroom',
    type: 'Private room',
    id: 7,
    price: 19,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/75be20cf-c288-4391-8fc5-76eaf7172fcc.jpg?aki_policy=xx_large'
  },
  {
    title: 'Heart of Richmond/Master bedroom',
    type: 'Private room',
    id: 8,
    price: 23,
    guests: 2,
    bedroom: 1,
    bath: 1,
    wifi: true,
    freeparking: false,
    kitchen: true,
    img: 'https://a0.muscache.com/im/pictures/47b90077-bdda-4b89-a85d-e69b39e1cea3.jpg?aki_policy=xx_large'
  },
] 